# -*- coding: utf-8 -*-
"""sales_performance_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwnqPYrJ6UObJxYmZJxtRlLNQL8wE6TS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/Sample - Superstore.csv',encoding='ISO-8859-1')

print(data.info())
print(data.describe())
print(data.isnull().sum())

data['Order Date']=pd.to_datetime(data['Order Date'])
data['Ship Date']=pd.to_datetime(data['Ship Date'])
data.drop_duplicates(inplace=True)

data['Order Month']=data['Order Date'].dt.month
data['Order year']=data['Order Date'].dt.year
data['Profit Margin']=data['Profit']/data['Sales']
data

plt.figure(figsize=(8,5))
sns.barplot(x='Region',y='Sales',data=data,estimator=sum)
plt.title('Total Sales by Region')
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='Category',y='Profit',data=data,estimator=sum)
plt.title('Total Profit by Category')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='Discount',y='Profit',hue='Category',data=data)
plt.title('Impact of Discount on Profit by Category')
plt.show()

monthly_sales=data.groupby(['Order year','Order Month'])['Sales'].sum().reset_index()
monthly_sales['Date'] = pd.to_datetime(monthly_sales['Order year'].astype(str) + '-' + monthly_sales['Order Month'].astype(str))
plt.figure(figsize=(12,6))
sns.lineplot(x='Date', y='Sales', data=monthly_sales)
plt.title('Monthly Sales Trend')
plt.show()

data.to_csv('cleaned_superstore_data.csv',index=False)